-- Run after the combined apple-store-notifications entitlement fixture.
CREATE TABLE IF NOT EXISTS public.app_updates(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title text);
ALTER TABLE public.app_updates ENABLE ROW LEVEL SECURITY;
\ir ../migrations/20260914120000_protected_app_access.sql
\ir ../migrations/20260914121000_sync_app_access_grants.sql
BEGIN;
INSERT INTO auth.users VALUES('00000000-0000-4000-8000-000000000001');
SELECT set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000001',true);
DO $$
DECLARE u uuid:=auth.uid(); k text:='production:'||repeat('a',64); t timestamptz:=now();
BEGIN
  INSERT INTO public.store_subscription_bindings VALUES('google_play',k,u);
  INSERT INTO public.google_play_subscription_state(subscription_key,store_state,expires_at,observed_at)
    VALUES(k,'SUBSCRIPTION_STATE_ACTIVE',t+interval '30 days',t);
  INSERT INTO public.twitch_account_bindings(user_id,twitch_user_id) VALUES(u,'20');
  INSERT INTO public.twitch_entitlement_state VALUES('20',t,false,t-interval '1 day');
  ASSERT (public.get_my_premium_entitlement()->>'is_premium')::boolean, 'Expired Twitch must not cancel Google';
  UPDATE public.google_play_subscription_state SET store_state='SUBSCRIPTION_STATE_EXPIRED',expires_at=t;
  UPDATE public.twitch_entitlement_state SET active=true,expires_at=t+interval '2 days';
  ASSERT (public.get_my_premium_entitlement()->>'is_premium')::boolean, 'Expired Google must not cancel Twitch';
  UPDATE public.twitch_entitlement_state SET expires_at=t;
  ASSERT NOT (public.get_my_premium_entitlement()->>'is_premium')::boolean;
  INSERT INTO public.store_subscription_bindings VALUES('app_store','production:7001',u);
  INSERT INTO public.apple_subscription_state VALUES('production:7001',1,t+interval '10 days',t);
  INSERT INTO public.stripe_customers VALUES('cus_matrix',u);
  INSERT INTO public.stripe_subscriptions VALUES('sub_matrix','cus_matrix','canceled',t,t);
  ASSERT (public.get_my_premium_entitlement()->>'is_premium')::boolean, 'Canceled Stripe must not cancel Apple';
  INSERT INTO public.app_access_grants(user_id,role) VALUES(u,'owner');
  INSERT INTO public.user_premium_status(user_id,is_premium,premium_source,premium_expires_at)
    VALUES(u,false,'stripe',t) ON CONFLICT(user_id) DO UPDATE SET is_premium=false,premium_source='stripe',premium_expires_at=t;
  ASSERT public.has_app_admin_access(u);
  ASSERT public.get_my_app_access()->>'role'='owner';
  UPDATE public.apple_subscription_state SET status=5;
  UPDATE public.user_premium_status SET is_premium=false,premium_source='google',premium_expires_at=t;
  ASSERT public.get_my_premium_entitlement()->>'premium_source'='developer';
  ASSERT (public.get_my_premium_entitlement()->>'premium_expires_at') IS NULL;
  UPDATE public.user_premium_status SET premium_source='twitch',premium_expires_at=t+interval '33 days';
  ASSERT (SELECT is_premium AND premium_source='developer' AND premium_expires_at IS NULL FROM public.user_premium_status WHERE user_id=u);
  ASSERT NOT has_table_privilege('authenticated','public.app_access_grants','UPDATE');
  ASSERT NOT has_table_privilege('authenticated','public.app_access_grants','INSERT');
END $$;
SET LOCAL ROLE authenticated;
DO $$ BEGIN
  ASSERT public.get_my_app_access()->>'role'='owner';
  INSERT INTO public.app_updates(title) VALUES('owner test');
  PERFORM set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000002',true);
  BEGIN
    INSERT INTO public.app_updates(title) VALUES('unauthorized');
    RAISE EXCEPTION 'Non-admin update allowed';
  EXCEPTION WHEN insufficient_privilege THEN NULL; END;
  BEGIN
    INSERT INTO public.app_access_grants(user_id,role) VALUES(auth.uid(),'owner');
    RAISE EXCEPTION 'Self-promotion allowed';
  EXCEPTION WHEN insufficient_privilege THEN NULL; END;
END $$;
RESET ROLE;
DO $$
DECLARE u uuid:='00000000-0000-4000-8000-000000000001';
BEGIN
  UPDATE public.app_access_grants SET revoked_at=now() WHERE user_id=u;
  ASSERT NOT public.has_app_admin_access(u);
  ASSERT NOT (public.effective_premium_entitlement(u)->>'is_premium')::boolean;
  UPDATE public.app_access_grants SET revoked_at=NULL WHERE user_id=u;
  ASSERT (public.effective_premium_entitlement(u)->>'is_premium')::boolean;
  DELETE FROM public.app_access_grants WHERE user_id=u;
  ASSERT NOT (public.effective_premium_entitlement(u)->>'is_premium')::boolean;
END $$;
ROLLBACK;
\echo Cross-provider and protected owner tests passed.
