// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6bB1hXaeSRYKxDs2tBwbVRxUk80ZYwD0',
    appId: '1:99712650730:web:5887f11fb438d861a93693',
    messagingSenderId: '99712650730',
    projectId: 'statusxp',
    authDomain: 'statusxp.firebaseapp.com',
    storageBucket: 'statusxp.firebasestorage.app',
    measurementId: 'G-ZYBPQ1QZPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyl5HukrbloLTZUXPYE1ZTY8hcTc8NKOg',
    appId: '1:99712650730:android:cafa59689d1dadb7a93693',
    messagingSenderId: '99712650730',
    projectId: 'statusxp',
    storageBucket: 'statusxp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmX2pNIhj_9zWDR5oNmu-wBcWHjwNRZ4w',
    appId: '1:99712650730:ios:f1c37cfa18832998a93693',
    messagingSenderId: '99712650730',
    projectId: 'statusxp',
    storageBucket: 'statusxp.firebasestorage.app',
    iosBundleId: 'com.statusxp.statusxp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmX2pNIhj_9zWDR5oNmu-wBcWHjwNRZ4w',
    appId: '1:99712650730:ios:f1c37cfa18832998a93693',
    messagingSenderId: '99712650730',
    projectId: 'statusxp',
    storageBucket: 'statusxp.firebasestorage.app',
    iosBundleId: 'com.statusxp.statusxp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6bB1hXaeSRYKxDs2tBwbVRxUk80ZYwD0',
    appId: '1:99712650730:web:de8e4611f5b70c06a93693',
    messagingSenderId: '99712650730',
    projectId: 'statusxp',
    authDomain: 'statusxp.firebaseapp.com',
    storageBucket: 'statusxp.firebasestorage.app',
    measurementId: 'G-XCB4659VLW',
  );
}
