BEGIN;

CREATE TABLE IF NOT EXISTS "public"."notifications" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "type" text NOT NULL,
  "title" text NOT NULL,
  "message" text NOT NULL,
  "data" jsonb,
  "is_read" boolean NOT NULL DEFAULT false,
  "read_at" timestamp with time zone,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "notifications_user_id_fkey"
    FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id") ON DELETE CASCADE
);

COMMENT ON TABLE "public"."notifications" IS 'In-app notifications for subscription and account lifecycle events.';

CREATE INDEX IF NOT EXISTS "idx_notifications_user_created_at"
  ON "public"."notifications" USING btree ("user_id", "created_at" DESC);

ALTER TABLE "public"."notifications" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "notifications_select_own" ON "public"."notifications";
CREATE POLICY "notifications_select_own"
  ON "public"."notifications"
  FOR SELECT
  USING ((SELECT auth.uid()) = "user_id");

DROP POLICY IF EXISTS "notifications_insert_own" ON "public"."notifications";
CREATE POLICY "notifications_insert_own"
  ON "public"."notifications"
  FOR INSERT
  WITH CHECK ((SELECT auth.uid()) = "user_id");

DROP POLICY IF EXISTS "notifications_update_own" ON "public"."notifications";
CREATE POLICY "notifications_update_own"
  ON "public"."notifications"
  FOR UPDATE
  USING ((SELECT auth.uid()) = "user_id")
  WITH CHECK ((SELECT auth.uid()) = "user_id");

DROP POLICY IF EXISTS "notifications_delete_own" ON "public"."notifications";
CREATE POLICY "notifications_delete_own"
  ON "public"."notifications"
  FOR DELETE
  USING ((SELECT auth.uid()) = "user_id");

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."notifications" TO "authenticated", "service_role";
GRANT USAGE, SELECT ON SEQUENCE "public"."notifications_id_seq" TO "authenticated", "service_role";

COMMIT;
