-- Create app_updates table for displaying app changelog/updates in settings
-- Simple table with title, description, and release date

CREATE TABLE IF NOT EXISTS "public"."app_updates" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" text NOT NULL,
    "description" text NOT NULL,
    "release_date" timestamp with time zone NOT NULL DEFAULT now(),
    "version" text,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
-- Add index for efficient querying by release_date
CREATE INDEX IF NOT EXISTS "app_updates_release_date_idx" ON "public"."app_updates" ("release_date" DESC);
-- Enable RLS
ALTER TABLE "public"."app_updates" ENABLE ROW LEVEL SECURITY;
-- Policy: Anyone can read app updates (no auth required)
CREATE POLICY "Anyone can view app updates" 
ON "public"."app_updates" 
FOR SELECT 
USING (true);
-- Policy: Only authenticated users with admin role can insert/update/delete
-- (For now, updates will be managed via SQL or Supabase Dashboard)
CREATE POLICY "Service role can manage app updates" 
ON "public"."app_updates" 
FOR ALL 
USING (auth.role() = 'service_role');
-- Add some initial sample updates
INSERT INTO "public"."app_updates" ("title", "description", "release_date", "version") VALUES
('Sync Resume Feature', 'Added automatic sync resume when app restarts after interruption. Syncs will now continue automatically if Railway resets or app crashes mid-sync.', '2026-01-22 00:00:00+00', '1.1.7'),
('My Games Sorting Fixed', 'Fixed "Last Trophy" sorting on My Games screen. Now properly sorts games by most recent trophy earned across all platforms.', '2026-01-22 00:00:00+00', '1.1.7'),
('Status Poster Performance', 'Improved Status Poster loading speed with optimized parallel queries. Added platform-specific rank badges under each platform pill.', '2026-01-22 00:00:00+00', '1.1.7');
COMMENT ON TABLE "public"."app_updates" IS 'Stores app update changelog entries for display in settings screen';
