CREATE TABLE IF NOT EXISTS public.referral_codes (
  user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  code text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT referral_codes_format CHECK (code ~ '^[A-Z0-9]{12}$')
);

CREATE TABLE IF NOT EXISTS public.user_referrals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  referrer_user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  referred_user_id uuid NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  referral_code text NOT NULL REFERENCES public.referral_codes(code),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'rewarded')),
  reward_credits integer NOT NULL DEFAULT 10 CHECK (reward_credits BETWEEN 1 AND 100),
  created_at timestamptz NOT NULL DEFAULT now(),
  rewarded_at timestamptz,
  CONSTRAINT referral_not_self CHECK (referrer_user_id <> referred_user_id)
);

CREATE INDEX IF NOT EXISTS user_referrals_referrer_idx
  ON public.user_referrals(referrer_user_id, status);

ALTER TABLE public.referral_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_referrals ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.referral_codes, public.user_referrals FROM anon, authenticated;

CREATE OR REPLACE FUNCTION public.get_my_referral_summary()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_user uuid := auth.uid();
  v_code text;
BEGIN
  IF v_user IS NULL THEN RAISE EXCEPTION 'Authentication required'; END IF;

  v_code := upper(substr(replace(v_user::text, '-', ''), 1, 12));
  INSERT INTO public.referral_codes(user_id, code)
  VALUES (v_user, v_code)
  ON CONFLICT (user_id) DO NOTHING;

  SELECT code INTO v_code FROM public.referral_codes WHERE user_id = v_user;
  RETURN jsonb_build_object(
    'code', v_code,
    'pending', (SELECT count(*) FROM public.user_referrals WHERE referrer_user_id = v_user AND status = 'pending'),
    'rewarded', (SELECT count(*) FROM public.user_referrals WHERE referrer_user_id = v_user AND status = 'rewarded'),
    'credits_earned', (SELECT coalesce(sum(reward_credits), 0) FROM public.user_referrals WHERE referrer_user_id = v_user AND status = 'rewarded'),
    'redeemed_code', (SELECT referral_code FROM public.user_referrals WHERE referred_user_id = v_user LIMIT 1)
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.redeem_referral_code(p_code text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_user uuid := auth.uid();
  v_referrer uuid;
  v_created timestamptz;
  v_profile public.profiles%ROWTYPE;
BEGIN
  IF v_user IS NULL THEN RAISE EXCEPTION 'Authentication required'; END IF;
  SELECT created_at INTO v_created FROM auth.users WHERE id = v_user;
  IF v_created < now() - interval '30 days' THEN
    RAISE EXCEPTION 'Referral codes are for new accounts';
  END IF;
  SELECT * INTO v_profile FROM public.profiles WHERE id = v_user;
  IF v_profile.last_psn_sync_at IS NOT NULL OR v_profile.last_xbox_sync_at IS NOT NULL OR v_profile.last_steam_sync_at IS NOT NULL THEN
    RAISE EXCEPTION 'Redeem the referral before your first sync';
  END IF;
  SELECT user_id INTO v_referrer
  FROM public.referral_codes
  WHERE code = upper(trim(p_code));
  IF v_referrer IS NULL THEN RAISE EXCEPTION 'Invalid referral code'; END IF;
  IF v_referrer = v_user THEN RAISE EXCEPTION 'You cannot redeem your own code'; END IF;

  INSERT INTO public.user_referrals(referrer_user_id, referred_user_id, referral_code)
  VALUES (v_referrer, v_user, upper(trim(p_code)));
  RETURN jsonb_build_object('success', true, 'status', 'pending');
EXCEPTION WHEN unique_violation THEN
  RAISE EXCEPTION 'A referral code has already been redeemed on this account';
END;
$$;

CREATE OR REPLACE FUNCTION public.finalize_my_referral_reward()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_user uuid := auth.uid();
  v_referral public.user_referrals%ROWTYPE;
  v_has_sync boolean;
BEGIN
  IF v_user IS NULL THEN RAISE EXCEPTION 'Authentication required'; END IF;
  SELECT * INTO v_referral
  FROM public.user_referrals
  WHERE referred_user_id = v_user
  FOR UPDATE;
  IF NOT FOUND OR v_referral.status = 'rewarded' THEN
    RETURN jsonb_build_object('rewarded', false, 'already_complete', FOUND);
  END IF;

  SELECT last_psn_sync_at IS NOT NULL OR last_xbox_sync_at IS NOT NULL OR last_steam_sync_at IS NOT NULL
  INTO v_has_sync FROM public.profiles WHERE id = v_user;
  IF NOT coalesce(v_has_sync, false) THEN
    RETURN jsonb_build_object('rewarded', false, 'reason', 'first_sync_required');
  END IF;

  INSERT INTO public.user_ai_credits(user_id, pack_credits)
  VALUES (v_referral.referrer_user_id, v_referral.reward_credits), (v_user, v_referral.reward_credits)
  ON CONFLICT (user_id) DO UPDATE
    SET pack_credits = public.user_ai_credits.pack_credits + EXCLUDED.pack_credits,
        updated_at = now();
  UPDATE public.user_referrals
  SET status = 'rewarded', rewarded_at = now()
  WHERE id = v_referral.id;
  RETURN jsonb_build_object('rewarded', true, 'credits', v_referral.reward_credits);
END;
$$;

REVOKE ALL ON FUNCTION public.get_my_referral_summary() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.redeem_referral_code(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.finalize_my_referral_reward() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_my_referral_summary() TO authenticated;
GRANT EXECUTE ON FUNCTION public.redeem_referral_code(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.finalize_my_referral_reward() TO authenticated;
